---

# Number of epochs to train
num_epochs: 50

# Output directory
output_dir: output

# Image folder with test images
image_folder_test: test

# Image folder with train images
image_folder_train: train

# How to start training
initialize: from-scratch # from-best-checkpoint, from-last-checkpoint, from-scratch

# Learning rate
learning_rate: 0.001

# Number of times to repeat the dataset
dataset_repetitions: 5
